.Dd June 11, 2025
.Dt LIFE 1
.Os
.Sh NAME
.Nm life
.Nd Game of Life
.Sh SYNOPSIS
.Nm
.Op Fl b Ar bits
.Op Fl c Ar num
.Op Fl g Ar num
.Op Fl l Ar num
.Ar input
.Op Ar output
.Sh DESCRIPTION
.Nm
acts out the Game of Life:
cells live in a grid on the surface of a torus
according to evolution rules.
By default, the grid is binary: a cell is either living or dead.
A dead cell surrounded by exactly two living neighbours becomes alive;
a living cell surrounded by less then two or more than three neigbours dies.
With the
.Fl b Ar bits
option, the cells consist of that many
.Ar bits
and the game is played at every bit.
.Pp
With the default of one bit,
the grid is displayed as a monochrome image.
With more than one but at most eight bits,
the grid is displayed in shades of gray.
With more than eight but at most twenty four bits,
the grid is displayed in RGB.
With more than twenty four but at most thirty two bits,
the remaining eight bits are interpreterd as transparency.
.Pp
The
.Ar input
is either a size description such as
.Sq 200x100 ,
meaning width and height,
or a text file or PNG file describing the initial population.
With a size description,
.Nm
will start with a randomly populated grid.
.Pp
If
.Ar input
is a PNG file, the grid size is inferred from the image size
and gets populated with the values of the image's pixels.
Otherwise,
.Ar input
is considered to be a text file
consisting of lines of numbers, separated by whitespace.
The numbers represent the initial content of the cells.
The number of bits is chosen to accomodate the highest number seen,
but can be overwritten with the
.Fl b
option.
The grid size is inferred from the number of lines and numbers.
The lines are required to contains the same number of values.
.Pp
If an
.Ar output
file is specified,
.Nm
will save the final population.
A file name ending with
.Sq png
determines the PNG format.
Otherwise, the output format will be textual.
.Nm
overwrites the output file without warning.
As a special case, an
.Ar input
or an
.Ar output
file name of
.Sq -
is recognized to mean standard input and standard output, respectively.
.Pp
The game keeps running while at least one cell is alive,
meaning at least one of the cell's bits is non-zero.
With the
.Fl g
option,
.Nm
will stop after at most that many generations.
With the
.Fl c Ar num
option,
.Nm
will check the previous
.Ar num
generations to see if the evolution has entered a loop
and will stop writing the output in that case.
By default,
.Nm
will continue to run even after a loop is entered;
use the
.Fl l
option to exit instead.
.Pp
The options are as follows:
.Pp
.Bl -tag -width xbxbits -compact
.It Fl b Ar bits
Use this many bits (32 at the most).
.It Fl c Ar num
Consider
.Ar num
previous generations to detect a loop.
.It Fl g Ar num
Stop after
.Ar num
generations.
.It Fl l
Stop once a loop is detected.
.El
.Sh AUTHORS
.An Jan Starý Aq Mt hans@stare.cz
